/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listaenlazada.proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Jeffrey
 */
public class Principal extends javax.swing.JFrame {

    //variable global de la clase funciones
    Funciones fn = new Funciones();
    
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        
        //se inhabilitan los botones correspondientes
        btnExtraer.setEnabled(false);
        btnMostrarElemento.setEnabled(false);
        btnVaciarCola.setEnabled(false);
        btnMostrarCola.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNumero = new javax.swing.JButton();
        btnExtraer = new javax.swing.JButton();
        btnMostrarElemento = new javax.swing.JButton();
        btnColaVacia = new javax.swing.JButton();
        btnTamanioCola = new javax.swing.JButton();
        btnMostrarCola = new javax.swing.JButton();
        btnVaciarCola = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTA ENLAZADA");

        btnNumero.setText("Insertar elemento");
        btnNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroActionPerformed(evt);
            }
        });

        btnExtraer.setText("Extraer elemento");
        btnExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerActionPerformed(evt);
            }
        });

        btnMostrarElemento.setText("Mostrar elemento (indicar índice)");
        btnMostrarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarElementoActionPerformed(evt);
            }
        });

        btnColaVacia.setText("¿La cola está vacía?");
        btnColaVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColaVaciaActionPerformed(evt);
            }
        });

        btnTamanioCola.setText("Tamaño actual de la cola");
        btnTamanioCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTamanioColaActionPerformed(evt);
            }
        });

        btnMostrarCola.setText("Mostrar todos los elementos");
        btnMostrarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarColaActionPerformed(evt);
            }
        });

        btnVaciarCola.setText("Vaciar cola");
        btnVaciarCola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarColaActionPerformed(evt);
            }
        });

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNumero)
                    .addComponent(btnExtraer)
                    .addComponent(btnMostrarElemento)
                    .addComponent(btnColaVacia)
                    .addComponent(btnTamanioCola)
                    .addComponent(btnMostrarCola)
                    .addComponent(btnVaciarCola)
                    .addComponent(btnSalir)
                    .addComponent(jLabel1))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btnNumero)
                .addGap(18, 18, 18)
                .addComponent(btnExtraer)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarElemento)
                .addGap(18, 18, 18)
                .addComponent(btnColaVacia)
                .addGap(18, 18, 18)
                .addComponent(btnTamanioCola)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarCola)
                .addGap(18, 18, 18)
                .addComponent(btnVaciarCola)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroActionPerformed
        try{
            String num = JOptionPane.showInputDialog(null, "Por favor ingrese un número entero", "Ingreso número entero",
                 JOptionPane.QUESTION_MESSAGE);
            
            //se convierte a entero
            int numero = Integer.parseInt(num);
            
            //inserta el elemento en la cola
            fn.insertar(numero);
            
            //se habilitan los botones correspondientes
            btnExtraer.setEnabled(true);
            btnMostrarElemento.setEnabled(true);
            btnVaciarCola.setEnabled(true);
            btnMostrarCola.setEnabled(true);

        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo NÚMEROS enteros. Intente de nuevo");
        }
    }//GEN-LAST:event_btnNumeroActionPerformed

    private void btnMostrarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarElementoActionPerformed
         try{
            String num = JOptionPane.showInputDialog(null, "Por favor digite el índice del número a mostrar", "Ingreso número entero",
                 JOptionPane.QUESTION_MESSAGE);
            
            //se convierte a entero
            int numero = Integer.parseInt(num);
            
            //inserta el elemento en la cola
            String dato = fn.mostrarEn(numero);
            fn.mostrarTodos();
            
            if(dato != null)
                JOptionPane.showMessageDialog(null, "El valor del índice consultado es: " + dato);
            else
                JOptionPane.showMessageDialog(null, "No existen datos en el índice consultado");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo NÚMEROS enteros. Intente de nuevo");
        }
    }//GEN-LAST:event_btnMostrarElementoActionPerformed

    private void btnExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerActionPerformed
         try{
            String num = JOptionPane.showInputDialog(null, "Por favor digite el índice del número a eliminar", "Ingreso número entero",
                 JOptionPane.QUESTION_MESSAGE);
            
            //se convierte a entero
            int numero = Integer.parseInt(num);
            
            //inserta el elemento en la cola
            String dato = fn.eliminar(numero);
            fn.mostrarTodos();
            
            if(dato != null)
                JOptionPane.showMessageDialog(null, "El valor del índice eliminado es: " + dato);
            else
                JOptionPane.showMessageDialog(null, "No existen datos en el índice consultado");
        }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Por favor ingrese solo NÚMEROS enteros. Intente de nuevo");
        }
    }//GEN-LAST:event_btnExtraerActionPerformed

    private void btnVaciarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarColaActionPerformed
        //se eliminan todos los elementos de la cola
        fn.borrarCola();
        JOptionPane.showMessageDialog(null, "Se ha vaciado la cola éxitosamente");
        
        //se inhabilitan los botones correspondientes
        btnExtraer.setEnabled(false);
        btnMostrarElemento.setEnabled(false);
        btnVaciarCola.setEnabled(false);
        btnMostrarCola.setEnabled(false);
        
    }//GEN-LAST:event_btnVaciarColaActionPerformed

    private void btnTamanioColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTamanioColaActionPerformed
        int tamanio = fn.tamanioCola();
        
        JOptionPane.showMessageDialog(null, "El tamaño de la cola es de " + tamanio);
    }//GEN-LAST:event_btnTamanioColaActionPerformed

    private void btnColaVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColaVaciaActionPerformed
        
        int tamanio = fn.tamanioCola();
        
        if(tamanio == 0)
            JOptionPane.showMessageDialog(null, "La cola está vacía");
        else
            JOptionPane.showMessageDialog(null, "La cola NO está vacía");
        
        
    }//GEN-LAST:event_btnColaVaciaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        Object[] opciones = {"SÍ", "NO"};
        Object defecto = opciones[1];
        
         int opcion = JOptionPane.showOptionDialog(null, "¿Está seguro de que desea salir?", "Advertencia",
                JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE, null, opciones, defecto);
         
         if(opcion == 0)
             this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnMostrarColaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarColaActionPerformed
        //se llama a la clase que pinta los nodos
        Grafico grafico = new Grafico(fn.head);
        grafico.setVisible(true);   
    }//GEN-LAST:event_btnMostrarColaActionPerformed
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColaVacia;
    private javax.swing.JButton btnExtraer;
    private javax.swing.JButton btnMostrarCola;
    private javax.swing.JButton btnMostrarElemento;
    private javax.swing.JButton btnNumero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTamanioCola;
    private javax.swing.JButton btnVaciarCola;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
