/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package listaenlazada.proyecto;

/**
 *
 * @author Jeffrey
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnNumero = new javax.swing.JButton();
        btnExtraer = new javax.swing.JButton();
        btnMostrarElemento = new javax.swing.JButton();
        btnColaVacia = new javax.swing.JButton();
        btnTamanioCola = new javax.swing.JButton();
        btnMostrarCola = new javax.swing.JButton();
        btnVaciarCola = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTA ENLAZADA");

        btnNumero.setText("Ingresar número entero");

        btnExtraer.setText("Extraer elemento");

        btnMostrarElemento.setText("Mostrar elemento (indicar índice)");

        btnColaVacia.setText("¿La cola está vacía?");

        btnTamanioCola.setText("Tamaño actual de la cola");

        btnMostrarCola.setText("Mostrar todos los elementos");

        btnVaciarCola.setText("Vaciar cola");

        btnSalir.setText("SALIR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnNumero)
                    .addComponent(btnExtraer)
                    .addComponent(btnMostrarElemento)
                    .addComponent(btnColaVacia)
                    .addComponent(btnTamanioCola)
                    .addComponent(btnMostrarCola)
                    .addComponent(btnVaciarCola)
                    .addComponent(btnSalir)
                    .addComponent(jLabel1))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addComponent(btnNumero)
                .addGap(18, 18, 18)
                .addComponent(btnExtraer)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarElemento)
                .addGap(18, 18, 18)
                .addComponent(btnColaVacia)
                .addGap(18, 18, 18)
                .addComponent(btnTamanioCola)
                .addGap(18, 18, 18)
                .addComponent(btnMostrarCola)
                .addGap(18, 18, 18)
                .addComponent(btnVaciarCola)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColaVacia;
    private javax.swing.JButton btnExtraer;
    private javax.swing.JButton btnMostrarCola;
    private javax.swing.JButton btnMostrarElemento;
    private javax.swing.JButton btnNumero;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnTamanioCola;
    private javax.swing.JButton btnVaciarCola;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
